### ISSUE TITLE
FAT Text Fehler beheben

### ISSUE THREAD

**Issue by RauschRobin** [ProducerJamer/Informatik-ABI-Zusammenfassung#28]
"Bei einer Sektorgröße von 512 Byte...." Satz is falsch(von Felix)

**Comment by RauschRobin** [comment]
Lieber schreiben: "Bei einer Clustergröße von 512 Byte..."
Felix meint da steht noch was drin was kein sinn macht

**Comment by ProducerJamer** [comment]
Hab Clustergröße geändert, der Rest ist sinngemäß ausm Buch
